### ISSUE TITLE
Total model should be extended from Mage_Sales_Model_Order_Total_Abstract

### ISSUE THREAD

**Issue by twosg** [PHOENIX-MEDIA/Magento-CashOnDelivery#38]
Getting this exception when trying to create an invoice for order in the admin area. Payment method was **NOT** COD.

Magento-Version: CE 1.9.3.6
Phoenix_CashOnDelivery-Version: 1.0.9

```
a:5:{i:0;s:85:"Gesamtsummen Model sollte die Klasse Mage_Sales_Model_Order_Total_Abstract erweitern.";i:1;s:2259:"#0 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Sales/Model/Order/Total/Config/Base.php(70): Mage::throwException('Gesamtsummen Mo...')
#1 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Sales/Model/Config/Ordered.php(83): Mage_Sales_Model_Order_Total_Config_Base->_initModelInstance('Phoenix_CashOnD...', 'phoenix_cashond...', Object(Mage_Core_Model_Config_Element))
#2 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Sales/Model/Order/Total/Config/Base.php(88): Mage_Sales_Model_Config_Ordered->_initModels()
#3 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Sales/Model/Order/Invoice.php(509): Mage_Sales_Model_Order_Total_Config_Base->getTotalModels()
#4 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Sales/Model/Service/Order.php(143): Mage_Sales_Model_Order_Invoice->collectTotals()
#5 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/Order/InvoiceController.php(86): Mage_Sales_Model_Service_Order->prepareInvoice(Array)
#6 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Adminhtml/controllers/Sales/Order/InvoiceController.php(177): Mage_Adminhtml_Sales_Order_InvoiceController->_initInvoice()
#7 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_Order_InvoiceController->newAction()
#8 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('new')
#9 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /home/dev/domains/mydomain.devserver.local/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#11 /home/dev/domains/mydomain.devserver.local/public_html/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#12 /home/dev/domains/mydomain.devserver.local/public_html/index.php(85): Mage::run('', 'store')
#13 {main}";s:3:"url";s:93:"/index.php/admin/sales_order_invoice/new/order_id/14992/key/8c45e345baba1a61912e3ffd8568cde4/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```

**Comment by PHOENIX-MEDIA** [comment]
Can you post the class in question. CoD total classes all inherit from Mage_Sales_Model_Order_Total_Abstract and I was not able to reproduce the issue after debugging. instanceof always returns the expected result.
